class ProxyServers:
    client_config_port = 0
    chat_port = 0
    accounts_port = 0
    publishing_content_port = 0
    scd_port = 0
    sieve_port = 0 #"https://sieve.services.riotcdn.net",
    lifecycle_port = 0
    loyalty_port = 0
    pcbs_loyalty_port = 0
    email_port = 0
    entitlements_port = 0
    ledge_port = 0
    player_platform_port = 0
    payments_port = 0
    fiddler_proxies = {}
    playerpreferences_port = 0
    geo_port = 0
    auth_port = 0
    authenticator_port = 0
